import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=path.join(root,'.runtime',`ui-check-${Date.now()}`);
process.env.SHIKIGAMI_DATA_DIR=data;
process.env.SHIKIGAMI_CODEX_CONFIG=path.join(data,'codex-test.toml');
await fs.mkdir(data,{recursive:true});
await fs.mkdir(path.join(root,'artifacts'),{recursive:true});
await fs.writeFile(process.env.SHIKIGAMI_CODEX_CONFIG,'model = "unchanged-test-model"\n');
const {ensureService}=await import('../src/service.mjs');
const session=await ensureService();
async function api(route,body){const r=await fetch(session.base+'/api/'+route,{method:body===undefined?'GET':'POST',headers:{'X-Shikigami-Token':session.token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json();}
const browser=await chromium.launch({channel:'chrome',headless:true});
const client=new Client({name:'shikigami-ui-check',version:'1'});
const errors=[];
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(session.panel);
  await page.getByText('Codexの接続待ち',{exact:true}).waitFor();
  await page.screenshot({path:path.join(root,'artifacts','app-onboarding.png'),fullPage:true});
  await page.locator('[data-page="connect"]').click();
  assert(await page.locator('#connect-button').isDisabled());
  await page.locator('#approve-browser').check();
  await page.locator('#connect-button').click();
  await page.locator('#connect-message').filter({hasText:'設定を追加しました。'}).waitFor();
  const config=await fs.readFile(process.env.SHIKIGAMI_CODEX_CONFIG,'utf8');
  assert(config.includes('unchanged-test-model'));
  assert(config.includes('[mcp_servers.shikigami.tools.browser_navigate]'));
  await page.locator('#show-config').click();
  await page.waitForFunction(()=>document.querySelector('#config-code').textContent.includes('[mcp_servers.shikigami]'));
  assert((await page.locator('#config-code').textContent()).includes('[mcp_servers.shikigami]'));
  await client.connect(new StdioClientTransport({command:process.execPath,args:[path.join(root,'src','mcp.mjs')],env:{...process.env},stderr:'pipe'}));
  await client.callTool({name:'browser_navigate',arguments:{url:session.base+'/fixture/1'}});
  await page.locator('[data-page="workspace"]').click();
  await page.getByText('接続済み · Codex',{exact:true}).waitFor();
  await page.locator('#view:not([disabled])').waitFor();
  await page.screenshot({path:path.join(root,'artifacts','app-workspace.png'),fullPage:true});
  await page.locator('#view').click();
  await page.locator('#preview:visible').waitFor();
  await page.screenshot({path:path.join(root,'artifacts','app-preview.png'),fullPage:true});
  await page.locator('#hide').click();
  assert(!await page.locator('#preview').isVisible());
  await page.locator('#stop').click();
  await page.locator('#resume:visible').waitFor();
  assert((await api('status')).stopped);
  await page.locator('#resume').click();
  await page.locator('#stop:visible').waitFor();
  assert(!(await api('status')).stopped);
  await page.locator('[data-page="verify"]').click();
  assert(await page.locator('#start').isVisible());
  await page.locator('[data-page="workspace"]').click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(root,'artifacts','app-mobile.png'),fullPage:true});
  assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Mobile horizontal overflow');
  await page.setViewportSize({width:1366,height:768});
  await page.screenshot({path:path.join(root,'artifacts','app-small-desktop.png'),fullPage:true});
  assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Desktop horizontal overflow');
  await api('run',{seconds:5,mode:'automatic'});
  for(let i=0;i<200;i++){await new Promise(r=>setTimeout(r,250));const s=await api('status');if(!s.diagnosticRunning){assert(s.lastReport?.success,JSON.stringify(s.lastReport));assert(s.lastReport.assertions>=9);break;}if(i===199)throw new Error('Diagnostic timed out');}
  await client.close();
  await api('shutdown',{});
  await page.getByText('アプリに接続できません',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  const result={ok:true,connectionFlow:true,isolatedConfig:true,previewShowHide:true,stopResume:true,mobile:true,diagnostic:true,offline:true,humanConcurrencySimulated:false};
  await fs.writeFile(path.join(root,'artifacts','ui-check.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));
}finally{await client.close().catch(()=>{});await browser.close();await api('shutdown',{}).catch(()=>{});}
